[functions]
  directory = "netlify/functions"
  # Include HTML files in function bundle
  included_files = ["netlify/functions/html/*.html"]

[[redirects]]
  from = "/secret/*"
  to = "/secret"
  status = 200
